

#ifndef MAKINGTETRIS_DEFINES_H
#define MAKINGTETRIS_DEFINES_H

#define SCREEN_WIDTH 36
#define SCREEN_HEIGHT 72
#define GAME_BORDER_WIDTH 36
#define GAME_BORDER_HEIGHT 72

#define ELEMENT_WIDTH 4
#define ELEMENT_HEIGHT 4

#define Number_Of_Element_On_Row GAME_BORDER_HEIGHT / ELEMENT_HEIGHT
#define Number_Of_Element_On_Column GAME_BORDER_WIDTH / ELEMENT_WIDTH

#define Number_Of_Types 7

#endif //MAKINGTETRIS_DEFINES_H
